name: Build and Deploy Java Function App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ...existing code...
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: mvn clean package

      - name: Create function app package
        run: |
          cd target/azure-functions/javafunctionapp-1738723791781
          ls -la
          zip -r ../../../functionapp.zip *
          

      # Upload the zipped artifact as a workflow artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: functionapp
          path: functionapp.zip
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      # Download the zipped artifact
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: functionapp
          path: .
          
      # ...existing code...
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function
        uses: azure/functions-action@v1
        with:
          app-name: javafunctionappjpazure
          package: functionapp.zip

